import jsPDF from "jspdf";
import "jspdf-autotable";

export function generateInvoicePDF(invoice) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  let y = margin;

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", margin, y);
  y += 12;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, margin, y);
  doc.text(`Status: ${invoice.status}`, 200 - margin, y, { align: "right" });
  y += 8;
  doc.text(`Issue Date: ${invoice.issueDate.slice(0, 10)}`, margin, y);
  doc.text(`Due Date: ${invoice.dueDate.slice(0, 10)}`, 200 - margin, y, {
    align: "right",
  });
  y += 12;

  // Client Info
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", margin, y);
  doc.setFont("helvetica", "normal");
  y += 6;
  doc.text(invoice.client.name, margin, y);
  y += 6;
  doc.text(invoice.client.email, margin, y);
  y += 6;
  doc.text(invoice.client.address, margin, y);
  y += 10;

  // Table
  const itemRows = invoice.items.map((item) => [
    item.name,
    item.quantity,
    `Php ${item.unitPrice.toFixed(2)}`,
    `Php ${(item.quantity * item.unitPrice).toFixed(2)}`,
  ]);

  doc.autoTable({
    startY: y,
    head: [["Item", "Qty", "Unit Price", "Subtotal"]],
    body: itemRows,
    styles: { fontSize: 11 },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: 255,
      fontStyle: "bold",
      // no global halign here
    },
    columnStyles: {
      0: { halign: "left" }, // Item (body)
      1: { halign: "center" }, // Qty
      2: { halign: "right" }, // Unit Price
      3: { halign: "right" }, // Subtotal
    },
    didParseCell: (data) => {
      // apply right-align to specific header cells
      if (
        data.section === "head" &&
        (data.column.index === 2 || data.column.index === 3)
      ) {
        data.cell.styles.halign = "right";
      }
    },
  });

  // Total
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Total: Php ${invoice.total.toFixed(2)}`, pageWidth - 10, finalY, {
    align: "right",
  });

  // Footer
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(150);
  doc.text("Generated by InvoiceApp", margin, 285);

  doc.save(`Invoice-${invoice.invoiceNumber}.pdf`);
}
